---
# Practicalli Clojure
site_name: Practicalli Clojure
site_url: https://practical.li/clojure
site_description: Practical guide to Clojure programming language and Clojure REPL driven development
site_author: Practicalli
copyright: Copyright &copy 2023  Practicali <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
repo_url: https://github.com/practicalli/clojure/
edit_uri: https://github.com/practicalli/clojure/edit/main/docs/

# Deployment
# remote_name: origin
remote_branch: gh-pages # deployment branch

# Theme and styling
theme:
  name: material
  logo: assets/images/practicalli-logo.png
  favicon: assets/favicon.svg
  features:
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - navigation.instant # Avoid page reloading for internal links
    - navigation.tracking # Update URL with anchor
    - navigation.indexes # Nav sections can have files
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Override theme
  # custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

## Additional styling
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html # Grids
  - footnotes # footnotes and abbreviations
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # keyboard keys
  - pymdownx.magiclink
  - def_list # lists
  - pymdownx.tasklist:
      custom_checkbox: true # checkboxes
  - toc:
      permalink: λ︎

## Plugins
plugins:
  # Explicitly add search plugin when defining plugins in this configuration file
  - search
  - callouts
  - glightbox # Image aligning
  - git-revision-date-localized: # Update and Creation date of each page
      # enable_creation_date: true
      fallback_to_build_date: true

  # Generate Social Cards via CI only
  # in assets/images/social
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS_GENERATE, true]

  # Redirect pages when moved or changed
  - redirects:
      redirect_maps:
        repl-driven-development.md: introduction/repl-workflow.md

# Footer / Social Media
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jr0cket/
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/messages/practicalli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practical_li
    - icon: fontawesome/brands/github
      link: https://github.com/practicalli
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/practicalli

# Navigation
nav:
  - Introduction:
      - Overview: index.md
      - Clojure in Fifteen Mins: introduction/clojure-in-15-minutes.md
      - REPL Workflow: introduction/repl-workflow.md
      - Concepts:
          - introduction/concepts/index.md
          - Functional vs Imperative: introduction/concepts/what-is-functional-programming.md
          - From The Author: introduction/concepts/clojure-made-simple.md
          # - introduction/concepts/purpose.md
      # - introduction/learning-clojure.md
      # - introduction/who-uses-clojure.md
      - Contributing: introduction/contributing.md
      - Writing Tips: introduction/writing-tips.md
  - Install:
      - install/index.md
      - Java Host: install/java.md
      - Clojure CLI: install/clojure-cli.md
      - Code Analysis: install/code-analysis.md
  - Clojure CLI:
      - clojure-cli/index.md
      - Configure: clojure-cli/configure.md
      - Community Tools: clojure-cli/community-tools.md
  - REPL:
      - clojure-cli/repl/index.md
      - clojure-cli/repl/coding-in-the-repl.md
      - clojure-cli/repl/using-project-or-library.md
      - clojure-cli/repl/help-at-the-repl.md
      - clojure-cli/repl/customize-rebel.md
      - clojure-cli/repl/troubleshooting.md
      # <!-- - clojure-cli/repl/repl-uncovered.md --> <!-- TODO rewrite -->
  - Clojure Projects:
      - clojure-cli/projects/index.md
      - clojure-cli/projects/create.md
      - clojure-cli/projects/add-libraries.md
      - clojure-cli/projects/namespace.md
      - clojure-cli/projects/rich-comments.md
      - REPL Startup: clojure-cli/projects/configure-repl-startup.md

  - Clojure Editors:
      - clojure-editors/index.md
      - Clojure LSP:
          - clojure-cli/install/clojure-lsp/index.md
          - Clojure LSP Snippets: clojure-cli/install/clojure-lsp/snippets.md
          - Practicalli Snippets: clojure-cli/install/clojure-lsp/practicalli-snippets.md
      - Editor Install Guides:
          - clojure-editors/editor-install-guides/index.md
          - clojure-editors/editor-install-guides/atom-protorepl.md
          # - clojure-editors/editor-install-guides/atom-proton.md
          - clojure-editors/editor-install-guides/emacs-spacemacs.md
          - clojure-editors/editor-install-guides/emacs.md
          - clojure-editors/editor-install-guides/neovim-conjure.md
          - clojure-editors/editor-install-guides/vim-plugins.md
          - clojure-editors/editor-install-guides/spacevim-fireplace.md
          - clojure-editors/editor-install-guides/spacevim-configuration.md
          - clojure-editors/editor-install-guides/vspacecode-calva.md
          - clojure-editors/editor-install-guides/vscode-calva.md
          - clojure-editors/editor-install-guides/intellij-cursive.md
      - Editor User Guides:
          - clojure-editors/editor-user-guides/index.md
          - clojure-editors/editor-user-guides/atom-protorepl.md
          # - clojure-editors/editor-user-guides/atom-proton.md
          - clojure-editors/editor-user-guides/emacs-spacemacs.md
          - clojure-editors/editor-user-guides/neovim-conjure.md
          - clojure-editors/editor-user-guides/spacevim-fireplace.md
          - clojure-editors/editor-user-guides/vspacecode-calva.md
          - clojure-editors/editor-user-guides/vscode-calva.md
          - clojure-editors/editor-user-guides/intellij-cursive.md
  - Data Inspectors:
      - clojure-cli/data-browsers/index.md
      - clojure-cli/data-browsers/clojure-inspector.md
      - Portal: clojure-cli/data-browsers/portal.md
      # - clojure-cli/data-browsers/reveal.md

  - Code Challenges:
      - coding-challenges/index.md
      - 4 Ever Clojure:
          - coding-challenges/4clojure/index.md
      - Exercism:
          - coding-challenges/exercism/index.md
          - coding-challenges/exercism/rna-transcription.md
          - coding-challenges/exercism/hamming.md
          - coding-challenges/exercism/space-age.md
          - Bob: coding-challenges/exercism/bob.md
            # - coding-challenges/exercism/bob-string-approach.md
            # - coding-challenges/exercism/bob-regular-expression-approach.md
      - CodeWars: coding-challenges/codewars/index.md
      - Advent Of Code: coding-challenges/advent-of-code.md
      - Simple projects:
          - simple-projects/index.md
          - Random Function: simple-projects/random-clojure-function.md
          - Salary Calculator: simple-projects/salary-calculator.md -->
          - Encoder Decode:
              - simple-projects/encode-decode/index.md
              - simple-projects/encode-decode/convert-boolean-values.md
              - simple-projects/encode-decode/caesar-cipher-rot13.md
              - simple-projects/encode-decode/rna-dna.md
              - simple-projects/encode-decode/clacks.md
          - Data Transform:
              - simple-projects/data-transformation/index.md
              - simple-projects/data-transformation/most-common-word.md
          - Kata:
              - simple-projects/tdd-kata/index.md
              - Recent Song list: simple-projects/tdd-kata/recent-song-list.md

  - Reference:
      - Crreative Coding:
          - reference/creative-coding/index.md
