name: "GitBook publish"

on:
  # Manually trigger workflow
  workflow_dispatch:

  # Run work flow conditional on linter workflow success
  workflow_run:
    workflows:
      - "MegaLinter"
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - '_book/**'
    branches:
      - main
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Gitbook
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Node Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: cache-${{ hashFiles('**/book.json') }}

      - name: Publish Website
        uses: tuliren/publish-gitbook@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub generated token
